//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDeDatos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_factura
    {
        public int id { get; set; }
        public int id_venta { get; set; }
        public int consecutivo { get; set; }
        public System.DateTime fecha { get; set; }
        public long precio_venta { get; set; }
    
        public virtual tb_ventas tb_ventas { get; set; }
    }
}
