//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDeDatos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ventas()
        {
            this.tb_factura = new HashSet<tb_factura>();
        }
    
        public int id { get; set; }
        public int id_vehiculo { get; set; }
        public int id_vendedor { get; set; }
        public int id_cliente { get; set; }
        public string placa { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_factura> tb_factura { get; set; }
        public virtual tb_vehiculo tb_vehiculo { get; set; }
        public virtual tb_vendedor tb_vendedor { get; set; }
    }
}
