//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPConcesionario.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_vehiculo()
        {
            this.tb_fotos = new HashSet<tb_fotos>();
        }
    
        public int id { get; set; }
        public string color { get; set; }
        public int modelo { get; set; }
        public string serie_chasis { get; set; }
        public string serie_motor { get; set; }
        public int id_marca { get; set; }
        public int id_categoria { get; set; }
        public int precio { get; set; }
        public int descuento { get; set; }
        public bool estado { get; set; }
        public int id_proveedor { get; set; }
    
        public virtual tb_categoria tb_categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_fotos> tb_fotos { get; set; }
        public virtual tb_marca tb_marca { get; set; }
        public virtual tb_proveedor tb_proveedor { get; set; }
    }
}
